[theme]
primaryColor="#4CAF50" # Un verde brillante para los botones y elementos clave
backgroundColor="#F0F8F0" # Un fondo verde muy claro
secondaryBackgroundColor="#FFFFFF" # Blanco para los contenedores/tarjetas
textColor="#262730" # Color de texto oscuro
font="sans serif"
[server]
customDomain = "www.nutrigoal.net"
